# generated by datamodel-codegen:
#   filename:  repository_update.json
#   timestamp: 2024-09-03T02:22:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Visibility(Enum):
    public = "public"
    private = "private"


class AdvancedSecurity(BaseModel):
    status: Optional[str] = Field(None, description="Can be `enabled` or `disabled`.")


class SecretScanning(BaseModel):
    status: Optional[str] = Field(None, description="Can be `enabled` or `disabled`.")


class SecretScanningPushProtection(BaseModel):
    status: Optional[str] = Field(None, description="Can be `enabled` or `disabled`.")


class SecretScanningNonProviderPatterns(BaseModel):
    status: Optional[str] = Field(None, description="Can be `enabled` or `disabled`.")


class SecurityAndAnalysis(BaseModel):
    advanced_security: Optional[AdvancedSecurity] = Field(
        None,
        description='Use the `status` property to enable or disable GitHub Advanced Security for this repository. For more information, see "[About GitHub Advanced Security](/github/getting-started-with-github/learning-about-github/about-github-advanced-security)."',
    )
    secret_scanning: Optional[SecretScanning] = Field(
        None,
        description='Use the `status` property to enable or disable secret scanning for this repository. For more information, see "[About secret scanning](/code-security/secret-security/about-secret-scanning)."',
    )
    secret_scanning_push_protection: Optional[SecretScanningPushProtection] = Field(
        None,
        description='Use the `status` property to enable or disable secret scanning push protection for this repository. For more information, see "[Protecting pushes with secret scanning](/code-security/secret-scanning/protecting-pushes-with-secret-scanning)."',
    )
    secret_scanning_non_provider_patterns: Optional[
        SecretScanningNonProviderPatterns
    ] = Field(
        None,
        description='Use the `status` property to enable or disable secret scanning non-provider patterns for this repository. For more information, see "[Supported secret scanning patterns](/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)."',
    )


class SquashMergeCommitTitle(Enum):
    PR_TITLE = "PR_TITLE"
    COMMIT_OR_PR_TITLE = "COMMIT_OR_PR_TITLE"


class SquashMergeCommitMessage(Enum):
    PR_BODY = "PR_BODY"
    COMMIT_MESSAGES = "COMMIT_MESSAGES"
    BLANK = "BLANK"


class MergeCommitTitle(Enum):
    PR_TITLE = "PR_TITLE"
    MERGE_MESSAGE = "MERGE_MESSAGE"


class MergeCommitMessage(Enum):
    PR_BODY = "PR_BODY"
    PR_TITLE = "PR_TITLE"
    BLANK = "BLANK"


class RepositoryUpdate(BaseModel):
    name: Optional[str] = Field(None, description="The name of the repository.")
    description: Optional[str] = Field(
        None, description="A short description of the repository."
    )
    homepage: Optional[str] = Field(
        None, description="A URL with more information about the repository."
    )
    private: Optional[bool] = Field(
        None,
        description="Either `true` to make the repository private or `false` to make it public. Default: `false`.  \n**Note**: You will get a `422` error if the organization restricts [changing repository visibility](https://docs.github.com/articles/repository-permission-levels-for-an-organization#changing-the-visibility-of-repositories) to organization owners and a non-owner tries to change the value of private.",
    )
    visibility: Optional[Visibility] = Field(
        None, description="The visibility of the repository."
    )
    security_and_analysis: Optional[SecurityAndAnalysis] = Field(
        None,
        description='Specify which security and analysis features to enable or disable for the repository.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see "[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)."\n\nFor example, to enable GitHub Advanced Security, use this data in the body of the `PATCH` request:\n`{ "security_and_analysis": {"advanced_security": { "status": "enabled" } } }`.\n\nYou can check which security and analysis features are currently enabled by using a `GET /repos/{owner}/{repo}` request.',
    )
    has_issues: Optional[bool] = Field(
        None,
        description="Either `true` to enable issues for this repository or `false` to disable them.",
    )
    has_projects: Optional[bool] = Field(
        None,
        description="Either `true` to enable projects for this repository or `false` to disable them. **Note:** If you're creating a repository in an organization that has disabled repository projects, the default is `false`, and if you pass `true`, the API returns an error.",
    )
    has_wiki: Optional[bool] = Field(
        None,
        description="Either `true` to enable the wiki for this repository or `false` to disable it.",
    )
    is_template: Optional[bool] = Field(
        None,
        description="Either `true` to make this repo available as a template repository or `false` to prevent it.",
    )
    default_branch: Optional[str] = Field(
        None, description="Updates the default branch for this repository."
    )
    allow_squash_merge: Optional[bool] = Field(
        None,
        description="Either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging.",
    )
    allow_merge_commit: Optional[bool] = Field(
        None,
        description="Either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits.",
    )
    allow_rebase_merge: Optional[bool] = Field(
        None,
        description="Either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging.",
    )
    allow_auto_merge: Optional[bool] = Field(
        None,
        description="Either `true` to allow auto-merge on pull requests, or `false` to disallow auto-merge.",
    )
    delete_branch_on_merge: Optional[bool] = Field(
        None,
        description="Either `true` to allow automatically deleting head branches when pull requests are merged, or `false` to prevent automatic deletion.",
    )
    allow_update_branch: Optional[bool] = Field(
        None,
        description="Either `true` to always allow a pull request head branch that is behind its base branch to be updated even if it is not required to be up to date before merging, or false otherwise.",
    )
    use_squash_pr_title_as_default: Optional[bool] = Field(
        None,
        description="Either `true` to allow squash-merge commits to use pull request title, or `false` to use commit message. **This property has been deprecated. Please use `squash_merge_commit_title` instead.",
    )
    squash_merge_commit_title: Optional[SquashMergeCommitTitle] = Field(
        None,
        description="Required when using `squash_merge_commit_message`.\n\nThe default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit).",
    )
    squash_merge_commit_message: Optional[SquashMergeCommitMessage] = Field(
        None,
        description="The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message.",
    )
    merge_commit_title: Optional[MergeCommitTitle] = Field(
        None,
        description="Required when using `merge_commit_message`.\n\nThe default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name).",
    )
    merge_commit_message: Optional[MergeCommitMessage] = Field(
        None,
        description="The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message.",
    )
    archived: Optional[bool] = Field(
        None,
        description="Whether to archive this repository. `false` will unarchive a previously archived repository.",
    )
    allow_forking: Optional[bool] = Field(
        None,
        description="Either `true` to allow private forks, or `false` to prevent private forks.",
    )
    web_commit_signoff_required: Optional[bool] = Field(
        None,
        description="Either `true` to require contributors to sign off on web-based commits, or `false` to not require contributors to sign off on web-based commits.",
    )
