# generated by datamodel-codegen:
#   filename:  tag.json
#   timestamp: 2024-09-04T17:32:49+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field


class Commit(BaseModel):
    sha: str
    url: AnyUrl


class Tag(BaseModel):
    name: str = Field(..., examples=["v0.1"])
    commit: Commit
    zipball_url: AnyUrl = Field(
        ..., examples=["https://github.com/octocat/Hello-World/zipball/v0.1"]
    )
    tarball_url: AnyUrl = Field(
        ..., examples=["https://github.com/octocat/Hello-World/tarball/v0.1"]
    )
    node_id: str
