# generated by datamodel-codegen:
#   filename:  topic.json
#   timestamp: 2024-09-04T17:38:38+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Topics(BaseModel):
    names: List[str]


class Topic(str):

    @classmethod
    def model_validate(cls, item: str) -> Topic:
        return cls(item)
